// <auto-generated />
namespace HairCut.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Barbers_BarberShop_Connection_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Barbers_BarberShop_Connection_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "202011080317060_Barbers_BarberShop_Connection_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
